puts 9.class
puts 9.class.superclass
puts 9.class.superclass.superclass
p 9.class.ancestors
puts [1,2,3].class
puts [1,2,3].class.superclass
puts [1,2,3].class
puts "jeb".class.superclass
p "jeb".class.ancestors